name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: cmake build
      run: |
        mkdir build
        cd  build
        cmake ../ -DCMAKE_BUILD_TYPE=Release
        cmake --build .

#    - uses: actions/upload-artifact@v3
#      with:
#        name: my-artifact
#        path: bin/
